### ISSUE TITLE
Doesn't work with Mask Elements

### ISSUE THREAD

**Issue by marci1988** [baschte/content-animations#17]
Hi, the parameters of aos are not rendered in the frontend if it is a Mask content element. The code for the animationsSettings is present in the Mask layout.

Must be something configured in the plugin?

**Comment by baschte** [comment]
Hi @marci1988 
i dont use mask so i can't tell you exactly whats the problem here. I guess the needed dataProcessor stuff of content-animations isn't added to the setup typoscript given by the mask extension. 

Here i found the [https://github.com/Gernott/mask/blob/main/Configuration/TypoScript/setup.typoscript](definition of a mask element) in the setup of their code. If you add the needed dataProcessors for content-animations it should work i guess. But i didn't tested it.
