### ISSUE TITLE
Animation footer labels are not displayed on content elements within container elements (TYPO3 v12 only)

### ISSUE THREAD

**Issue by zenoussi** [baschte/content-animations#19]
<img width="1171" alt="Bildschirmfoto 2023-11-13 um 21 06 45" src="https://github.com/baschte/content-animations/assets/4442136/e18624de-5657-4e3c-b4ff-501a95c608c9">

- TYPO3 12.4.7
- PHP 8.1.13
- container 2.3.1
- content_defender 3.4.1

**Comment by baschte** [comment]
Hey @zenoussi,
the problem here is that the container extension overrides the rendering of an content element within a container. i cant change the behaviour so if you want to have the animation label you have to set another `gridPartialPath` within your container registration.

Ive tested it and it works again after i set:
`->addGridPartialPath('EXT:content_animations/Resources/Private/TemplateOverrides/typo3/cms-backend/Partials')`
to my container registration.

hope it helps you!

**Comment by zenoussi** [comment]
Thank you for your suggested solution. I think that it can't be the EXT:container alone, because the same version 2.3.1 displays the animation label under TYPO3 v11.5, see screenshot.
Maybe you can think of something else or with the support of b13?
![Bildschirmfoto 2023-11-15 um 12 05 51](https://github.com/baschte/content-animations/assets/4442136/2e2c8dc9-0ae3-4572-9204-bf0e1f142aed)

**Comment by baschte** [comment]
Hey @zenoussi,
yes thats right and below TYPO3 version 12 everything is working finde because the rendering of the page module is different. There are a lot changes in TYPO3 12 which makes me impossible. Talked with a main dev from container yesterday and its because container did some stuff on 12 which i cant prevent or override myself. You have to do it for 12 projects within your container definition.

**Comment by baschte** [comment]
hey @zenoussi,
i think i found a generic way to add the footer preview for all Elements within a container element.
To be sure you can install `content_animation:dev-feature/container-footer-label` branch and test if its working in your project. My tests are successful and fine.

greetings

**Comment by zenoussi** [comment]
hey @baschte,
I tested your branch and it works - great!

- TYPO3 12.4.8
- PHP 8.1.13
- container 2.3.1
- content_defender 3.4.1

Thanks a lot and I'm looking forward to the release.
Ulli

<img width="960" alt="Bildschirmfoto 2023-11-22 um 12 31 12" src="https://github.com/baschte/content-animations/assets/4442136/987ee2d5-c50e-40b0-9a29-37d3d6852fdb">

**Comment by zenoussi** [comment]
hey @baschte,
would you release your changes?

Thanks a lot
Ulli

**Comment by baschte** [comment]
Hey @zenoussi 
new version is out! :-)

Sorry for this delay.

Best regards.
